services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    links:
      - celery_worker
    depends_on:
      - rabbitmq
      - celery_worker

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:alpine
    ports:
      - 5672:5672
    restart: always
    env_file:
      - ./.env.dev

  celery_worker:
    container_name: celery
    build:
      context: ./backend
    command: celery -A celery_worker worker --loglevel=info
    environment:
      - WORKER_CONTAINER=TRUE
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    restart: always
    links:
      - rabbitmq
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq

  flower:
    container_name: flower
    image: mher/flower:0.9.5
    command: [ "flower", "--broker=amqp://rabbitmq:5672", "--port=5555", "--url_prefix=flower" ]
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq
      - celery_worker